# Generated by Django 4.0.2 on 2022-02-20 09:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DEPTNAME', models.CharField(max_length=30)),
                ('LOCATION', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ENUMBER', models.IntegerField()),
                ('ENAME', models.CharField(max_length=20)),
                ('JOININGDATE', models.DateField(default=django.utils.timezone.now)),
                ('ESALARY', models.FloatField()),
                ('EADDRESS', models.CharField(max_length=30)),
                ('DEPT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_department', to='DRFAPP.department')),
            ],
        ),
    ]
