# Generated by Django 4.0.2 on 2022-03-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRFAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_ID', models.CharField(max_length=30)),
                ('TIMESTAMP', models.DateTimeField()),
                ('HEART_RATE', models.IntegerField()),
                ('RESP_RATE', models.IntegerField()),
                ('ACTIVITY', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='DEPT',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
